let expert = Expert()
world.place(expert, atColumn: 1, row: 5)
for i in 1 ... 2 {
    expert.turnLeft()
}
expert.moveForward()
expert.collectGem()
expert.turnRight()
expert.moveForward()
expert.turnLockUp()
expert.turnRight()
expert.move(distance: 5)
expert.turnRight()
expert.moveForward()
expert.collectGem()
expert.turnLeft()
expert.turnLeft()
expert.moveForward()
expert.turnLockUp()
expert.turnRight()
expert.moveForward()
expert.move(distance: 5)
expert.collectGem()